# Generated by Django 4.1.2 on 2022-12-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='new_out_pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('student_id', models.CharField(max_length=50)),
                ('main_reason', models.CharField(max_length=50)),
                ('today_date', models.CharField(max_length=50)),
                ('out_data', models.CharField(max_length=50)),
                ('dis', models.TextField(max_length=300)),
                ('response', models.CharField(default='pending', max_length=50)),
                ('faculty_id', models.CharField(default='none', max_length=50)),
                ('Rejected_reason', models.CharField(default='none', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student_avatars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('student_image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
