# Generated by Django 4.1.2 on 2022-12-31 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_access', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_avatars',
            old_name='student_image',
            new_name='student_img',
        ),
    ]
