# Generated by Django 4.1.2 on 2023-01-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_access', '0005_new_out_pass_out_pass_id_alter_new_out_pass_dis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_out_pass',
            name='student_in',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='new_out_pass',
            name='student_out',
            field=models.CharField(default='none', max_length=500),
        ),
    ]
