# Generated by Django 4.1.2 on 2022-12-31 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_access', '0002_rename_student_image_student_avatars_student_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_avatars',
        ),
    ]
