# Generated by Django 4.1.2 on 2022-12-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_access', '0003_delete_student_avatars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=500)),
                ('student_img', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
