# Generated by Django 4.1.2 on 2022-12-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_access', '0004_student_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_out_pass',
            name='out_pass_id',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='new_out_pass',
            name='dis',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='new_out_pass',
            name='first_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='new_out_pass',
            name='last_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='new_out_pass',
            name='main_reason',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='new_out_pass',
            name='out_data',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='new_out_pass',
            name='student_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='new_out_pass',
            name='today_date',
            field=models.CharField(max_length=500),
        ),
    ]
