# Generated by Django 4.1.2 on 2023-01-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_access', '0006_new_out_pass_student_in_new_out_pass_student_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_images',
            name='student_img',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
