# Generated by Django 4.1.2 on 2023-01-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_access', '0007_alter_student_images_student_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_out_pass',
            name='qrcode',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
