# Generated by Django 4.1.2 on 2023-01-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_access', '0008_new_out_pass_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_out_pass',
            name='qr_image_name',
            field=models.CharField(default='none', max_length=500),
        ),
    ]
