# Generated by Django 4.1.2 on 2022-12-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_photos',
            name='student_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
