# Generated by Django 4.1.2 on 2022-12-31 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_account', '0002_student_photos_student_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student_photos',
        ),
    ]
